---
all:
  children:
    production_hosts:
      hosts:
        prod01:
          ansible_host: vps01.tuinstra.dev
          ansible_user: mtuinstra
          production_backup_host_slug: tuinstra-prod-01
          production_backup_pull_public_key_file: "{{ production_backup_public_key_root }}/prod01.pub"
        prod02:
          ansible_host: vps02.tuinstra.dev
          ansible_user: mtuinstra
          production_backup_host_slug: tuinstra-prod-02
          production_backup_pull_public_key_file: "{{ production_backup_public_key_root }}/prod02.pub"
