#!/usr/bin/env python3
"""DEV-34 Linux/root native rehearsal with owned synthetic targets only.

The local forced-command transport executes the real coordinator/target and
producer dispatch code; it is not an SSH trust/connection test. Source payload
must be the synthetic retained fixture generated by test_isolated_restore_native.
No installed production paths, keys, DNS connections or published ports are used.
"""
from __future__ import annotations

import argparse
import io
import json
import os
from pathlib import Path
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import time
import uuid

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / 'backup'))
sys.path.insert(0, str(REPO / 'scripts'))
import tuinstra_backup as backup
import production_restore as restore
import production_restore_target as target
import test_isolated_restore_native as native

PG = native.PG_IMAGE
UMAMI = native.UMAMI_IMAGE
CADDY = 'docker.io/library/caddy:2.10.2-alpine@sha256:4c6e91c6ed0e2fa03efd5b44747b625fec79bc9cd06ac5235a779726618e530d'
HOST, APP = native.HOST, native.APP


def write(path: Path, value: str | bytes, mode: int = 0o600) -> None:
    native.root_write(path, value.encode() if isinstance(value, str) else value, mode)


def checked(argv: list[str], **kwargs) -> subprocess.CompletedProcess:
    result = subprocess.run(argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
    if result.returncode:
        raise RuntimeError(f'fixture command failed: {Path(argv[0]).name}')
    return result


def compose(root: Path, *args: str, edge: bool = False) -> list[str]:
    file = root / ('caddy/compose.yml' if edge else 'app/compose.yml')
    command = ['/usr/bin/docker', 'compose', '--file', str(file)]
    if not edge:
        command += ['--project-name', json.loads((root / 'fixture.json').read_text())['project']]
    return command + list(args)


def database(root: Path, sql: str) -> bytes:
    return checked(compose(root, 'exec', '-T', 'db', 'sh', '-eu', '-c',
                   'exec psql -X -t -A --set=ON_ERROR_STOP=1 --username="$POSTGRES_USER" --dbname="$POSTGRES_DB"'),
                   input=sql.encode(), timeout=60).stdout.strip()


def traffic(root: Path, expected: int) -> None:
    # Native HTTPS with only the owned synthetic Caddy CA. The app may be
    # stopped during maintenance, so use a disposable probe on its private net.
    certificate = root / 'caddy-data/caddy/pki/authorities/local/root.crt'
    if not certificate.is_file():
        raise RuntimeError('fixture Caddy certificate is not ready')
    ca = certificate.read_text()
    project = json.loads((root / 'fixture.json').read_text())['project']
    script = ("const https=require('https');const request=https.get({hostname:'caddy',"
              "servername:'umami.tuinstra.dev',path:'/api/heartbeat',"
              "headers:{Host:'umami.tuinstra.dev'},ca:" + json.dumps(ca) +
              "},response=>{console.log(response.statusCode);response.resume();});"
              "request.on('error',()=>process.exit(1));request.setTimeout(10000,()=>request.destroy());")
    result = checked(['/usr/bin/docker', 'run', '--rm', '--interactive', '--network', project+'-data',
                      '--entrypoint', 'node', UMAMI], input=script.encode(), timeout=30)
    if result.stdout.strip() != str(expected).encode():
        raise RuntimeError('fixture Caddy traffic outcome did not match')


def build(source: Path) -> tuple[Path, dict, target.TargetConfig]:
    if (source.is_symlink() or source.parent != Path('/tmp') or not source.name.startswith('dev33-native-')
            or source.stat().st_uid != 0 or source.stat().st_mode & 0o077):
        raise RuntimeError('source is not the owned synthetic native fixture')
    for image in (PG, UMAMI, CADDY):
        checked(['/usr/bin/docker', 'image', 'inspect', image])
    if shutil.disk_usage('/tmp').free < 4 * 1024**3:
        raise RuntimeError('native fixture capacity unavailable')
    root = Path(tempfile.mkdtemp(prefix='dev34-native-', dir='/tmp'))
    project = 'dev34-' + uuid.uuid4().hex[:16]
    native.atomic_json(root / 'fixture.json', {'project': project, 'synthetic': True})
    payload = root / 'payload'
    shutil.copytree(source / 'payload', payload)
    for name in ('app', 'secrets', 'data/postgres', 'staging', 'journal', 'maintenance', 'host-locks',
                 'incoming', 'ingest', 'operations', 'producer-spool', 'producer-receipts', 'producer-work'):
        (root / name).mkdir(mode=0o700, parents=True, exist_ok=True)
    lock = root / 'host-locks' / f'operations.host.{HOST}.lock'
    lock.touch(mode=0o660); lock.chmod(0o660)
    target_lock = root / 'target.lock'
    target_lock.touch(mode=0o660); target_lock.chmod(0o660)
    write(payload / 'files/compose', f'''services:
  db:
    image: {PG}
    user: '70:70'
    env_file: [{root}/secrets/postgres.env]
    volumes: [{root}/data/postgres:/var/lib/postgresql/data]
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"']
      interval: 2s
      timeout: 2s
      retries: 30
    networks: [data]
  umami:
    image: {UMAMI}
    env_file: [{root}/secrets/umami.env]
    depends_on:
      db: {{condition: service_healthy}}
    read_only: true
    tmpfs: ['/tmp:rw,noexec,nosuid,size=64m']
    networks: [data]
networks:
  data: {{internal: true, name: {project}-data}}
''')
    envfile = payload / 'files/umami-env'
    write(envfile, envfile.read_text().replace('@127.0.0.1:5432/', '@db:5432/'))
    manifest = json.loads((payload / 'backup-manifest.json').read_text())
    for item in manifest['inputs']:
        file = payload / item['name']
        item.update(sha256=backup.sha256(file), bytes=file.stat().st_size)
    native.atomic_json(payload / 'backup-manifest.json', manifest)
    route = root / 'caddy/sites/umami.caddy'
    write(route, 'umami.tuinstra.dev {\n reverse_proxy umami:3000\n}\n', 0o644)
    write(root / 'caddy/Caddyfile', '{\n local_certs\n skip_install_trust\n}\nimport sites/*.caddy\n', 0o644)
    write(root / 'caddy/compose.yml', f'''name: {project}-edge
services:
  caddy:
    image: {CADDY}
    volumes: [{root}/caddy:/etc/caddy:ro, {root}/caddy-data:/data, {root}/caddy-config:/config]
    extra_hosts: ['umami.tuinstra.dev:127.0.0.1']
    networks: [data]
networks:
  data: {{external: true, name: {project}-data}}
''', 0o644)
    identity = root / 'age-identity.txt'
    write(identity, (source / 'age-identity.txt').read_bytes())
    recipient = checked(['age-keygen', '-y', str(identity)]).stdout
    write(root / 'age-recipient.txt', recipient, 0o640)
    os.chown(root / 'age-recipient.txt', 0, 82)
    write(root / 'passwords' / HOST / f'{APP}.password', uuid.uuid4().hex+'\n')
    files = {'compose': root / 'app/compose.yml', 'postgres-env': root / 'secrets/postgres.env',
             'umami-env': root / 'secrets/umami.env', 'database-password': root / 'secrets/database-password',
             'app-secret': root / 'secrets/app-secret', 'two-factor-encryption-key': root / 'secrets/two-factor-encryption-key',
             'admin-password': root / 'secrets/admin-password'}
    producer = {'schema_version': 1, 'host_slug': HOST, 'spool_dir': str(root/'producer-spool'),
                'receipt_dir': str(root/'producer-receipts'), 'work_dir': str(root/'producer-work'),
                'age_recipient_file': str(root/'age-recipient.txt'), 'lock_file': str(root/'producer.lock'),
                'spool_quota_bytes': 1024**3, 'production_restore_maintenance_root': str(root/'maintenance'),
                'applications': [{'app_id': APP, 'enabled': True, 'adapter': 'postgres-compose-v1',
                                  'compose_project': project, 'compose_file': str(root/'app/compose.yml'),
                                  'postgres_service': 'db', 'application_service': 'umami',
                                  'approved_images': {'db': PG, 'umami': UMAMI},
                                  'included_files': [{'name': name, 'path': str(path)} for name,path in files.items()]}]}
    native.atomic_json(root / 'producer.json', producer)
    engine = root / 'backup-engine'
    write(engine, f'#!/bin/sh\nexec /usr/bin/python3 {shlex.quote(str(REPO / "backup/tuinstra_backup.py"))} "$@"\n', 0o700)
    binroot = root / 'bin'
    write(binroot / 'ssh', f'''#!/usr/bin/python3
import os,sys
if len(sys.argv)<3 or sys.argv[-2] != 'fixture@source.invalid': raise SystemExit(64)
os.execv('/usr/bin/python3', ['/usr/bin/python3', {str(REPO/'backup/tuinstra_backup.py')!r}, '--config',
    {str(root/'producer.json')!r}, 'dispatch', '--original-command', sys.argv[-1]])
''', 0o700)
    os.environ['PATH'] = str(binroot) + ':' + os.environ['PATH']
    cfg = {'schema_version': 1, 'hosts': [{'host_slug': HOST, 'applications': [APP], 'ssh_host': 'source.invalid',
                                         'ssh_user': 'fixture', 'identity_file': str(root/'unused-synthetic-key'),
                                         'known_hosts_file': str(root/'unused-known-hosts')}],
           'repository_root': str(root/'repository'), 'password_root': str(root/'passwords'),
           'catalog_root': str(root/'catalog'), 'policy_root': str(root/'policies'), 'max_artifact_bytes': 1024**3,
           'incoming_root': str(root/'incoming'), 'ingest_root': str(root/'ingest'),
           'operation_lock_root': str(root/'operations'), 'pull_lock_root': str(root/'pull-locks'),
           'host_lock_root': str(root/'host-locks'), 'age_identity_file': str(identity),
           'evidence_root': str(root/'evidence'), 'restore_adapter': str(REPO/'backup/restore-umami'),
           'restore_work_dir': f'/run/tuinstra-backup/{project}/work', 'restore_lock_file': str(root/'restore.lock'),
           'materialized_root': str(root/'materialized'), 'production_restore_work_root': str(root/'work'),
           'production_restore_journal_root': str(root/'coordinator-journal'),
           'executable': str(engine), 'installed_config': str(root/'worker.json')}
    # Use the actual bounded Console policy contract; all data/resources remain synthetic.
    policy = {'policy_version': 'production-v1', 'host_slug': HOST, 'app_id': APP}
    native.atomic_json(root/'policies'/HOST/f'{APP}.json', {**policy, 'plan_hash': backup.document_hash(policy)})
    native.atomic_json(root/'worker.json', cfg)
    tc = target.TargetConfig(stage_root=root/'staging', journal_root=root/'journal', app_root=root/'app',
                            secret_root=root/'secrets', data_root=root/'data', caddy_route=route,
                            caddy_compose=root/'caddy/compose.yml', producer_engine=engine,
                            producer_config=root/'producer.json', host_lock=target_lock,
                            maintenance_root=root/'maintenance', maximum_stage_bytes=1024**3, compose_project=project)
    return root, cfg, tc


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-fixture', required=True)
    parser.add_argument('--keep-fixture', action='store_true')
    args = parser.parse_args()
    if sys.platform != 'linux' or os.geteuid() != 0:
        raise RuntimeError('run only as root in disposable Linux runtime')
    baseline = native.inventory()
    root, cfg, tc = build(Path(args.source_fixture))
    report = {'suite': 'DEV-34 native coordinator/target rehearsal', 'fixture_path': str(root),
              'synthetic': True, 'transport': 'local forced-command; SSH trust not tested', 'scenarios': []}
    native.atomic_json(root/'report.json', report)
    try:
        adapter = target.UmamiAdapter(tc)
        adapter.apply(root/'payload', 'fixture-setup')
        database(root, "CREATE TABLE dev34_rehearsal_marker(proof text NOT NULL); INSERT INTO dev34_rehearsal_marker VALUES ('A');")
        checked(compose(root, 'up', '-d', edge=True), timeout=60)
        for _ in range(30):
            try:
                traffic(root, 200); break
            except RuntimeError:
                time.sleep(1)
        else:
            raise RuntimeError('fixture traffic did not become ready')
        producer = json.loads((root/'producer.json').read_text())
        point = backup.create_export(producer, APP)
        incoming = root/'incoming'/point['artifact_id']; incoming.mkdir(mode=0o700)
        for source, destination in ((root/'producer-spool'/f"{point['artifact_id']}.json", incoming/'manifest.json'),
                                    (root/'producer-spool'/f"{point['artifact_id']}.age", incoming/'payload.age')):
            write(destination, source.read_bytes())
        stored = backup.ingest_artifact(cfg, HOST, APP, point['artifact_id'], str(uuid.uuid4()), 'manual')
        evidence = json.loads(checked([str(root/'backup-engine'), '--config', str(root/'worker.json'),
                             'restore-test', '--host', HOST, '--app', APP, '--snapshot', stored['snapshot_id']],
                             timeout=900).stdout)
        if evidence['restore_status'] != 'passed': raise RuntimeError('real isolated restore failed')
        report['scenarios'].append({'scenario':'actual encrypted A export and isolated restore', 'status':'PASS',
                                    'snapshot_id':stored['snapshot_id'], 'artifact_id':point['artifact_id']})
        database(root, "UPDATE dev34_rehearsal_marker SET proof='B';")
        operation = 'restore-' + str(uuid.uuid4())
        request = restore.RestoreRequest.create(cfg, HOST, APP, stored['snapshot_id'], operation, 'a'*64)
        class LocalTransport(restore.RemoteTransport):
            def _call(self, command, stream=None):
                return target.dispatch(tc, command, stream if stream is not None else io.BytesIO(), adapter)
        transport = LocalTransport(cfg, request)
        store = restore.JournalStore(root/'coordinator-journal')
        restore.preflight(cfg, request, store, transport)
        def safety(exact, artifact, descriptor):
            traffic(root,503)
            return restore.safety_pull(cfg, exact, artifact, descriptor)
        result = restore.apply(cfg, request, store, transport, safety)
        assert result['state'] == 'succeeded' and database(root,'SELECT proof FROM dev34_rehearsal_marker;') == b'A'
        traffic(root,200)
        report['scenarios'].append({'scenario':'populated B safety backup before restore A', 'status':'PASS',
                                    'safety_snapshot_id':result['safety_snapshot_id']})
        rollback_hash = 'b'*64
        result = restore.rollback(cfg, request, rollback_hash, store, transport,
                                  lambda snapshot,purpose,descriptor: restore.stage_rollback(
                                      cfg,request,rollback_hash,transport,snapshot,purpose,descriptor))
        assert result['state']=='rolled-back' and database(root,'SELECT proof FROM dev34_rehearsal_marker;') == b'B'
        traffic(root,200)
        report['scenarios'].append({'scenario':'rollback after successful A restores pinned B', 'status':'PASS'})
        # Full empty-target route, preserving this fixture's previous B data.
        checked(compose(root, 'down'), timeout=60)
        os.replace(root/'data/postgres', root/'data/retained-empty-prerequisite')
        empty_operation = 'restore-' + str(uuid.uuid4())
        empty_request = restore.RestoreRequest.create(cfg, HOST, APP, stored['snapshot_id'], empty_operation, 'c'*64)
        empty_transport = LocalTransport(cfg, empty_request)
        restore.preflight(cfg, empty_request, store, empty_transport)
        empty_result = restore.apply(cfg, empty_request, store, empty_transport,
                                     lambda *_: (_ for _ in ()).throw(RuntimeError('empty target must not request a safety export')))
        assert empty_result['target_state']=='empty' and empty_result['safety_snapshot_id']=='0'*64
        assert empty_result['safety_artifact_id'] is None and database(root,'SELECT proof FROM dev34_rehearsal_marker;')==b'A'
        traffic(root,200)
        report['scenarios'].append({'scenario':'full explicitly empty target restore without fictional safety backup', 'status':'PASS'})
        # Target completes once; the coordinator loses the apply response.
        database(root, "UPDATE dev34_rehearsal_marker SET proof='C';")
        lost_operation = 'restore-' + str(uuid.uuid4())
        lost_request = restore.RestoreRequest.create(cfg, HOST, APP, stored['snapshot_id'], lost_operation, 'd'*64)
        class LostResponseTransport(LocalTransport):
            lost = False
            apply_calls = 0
            def _call(self, command, stream=None):
                value = super()._call(command, stream)
                if command.startswith('apply '):
                    self.apply_calls += 1
                    if not self.lost:
                        self.lost = True
                        raise restore.TransportUncertain('controlled loss after real target completion')
                return value
        lost_transport = LostResponseTransport(cfg, lost_request)
        restore.preflight(cfg,lost_request,store,lost_transport)
        try:
            restore.apply(cfg,lost_request,store,lost_transport,safety)
            raise RuntimeError('controlled lost response was not observed')
        except restore.TransportUncertain:
            pass
        assert store.load(lost_operation)['state']=='uncertain'
        try:
            restore.apply(cfg,lost_request,store,lost_transport,safety)
            raise RuntimeError('uncertain operation was replayed')
        except restore.RestoreError:
            pass
        reconciled=restore.status(cfg,lost_request,store,lost_transport)
        assert reconciled['state']=='succeeded' and lost_transport.apply_calls==1
        assert database(root,'SELECT proof FROM dev34_rehearsal_marker;')==b'A'
        traffic(root,200)
        report['scenarios'].append({'scenario':'lost apply response refuses replay and reconciles exact native terminal evidence', 'status':'PASS'})

        # Controlled failure between real data validation and the target receipt.
        database(root, "UPDATE dev34_rehearsal_marker SET proof='D';")
        failed_operation='restore-'+str(uuid.uuid4())
        failed_request=restore.RestoreRequest.create(cfg,HOST,APP,stored['snapshot_id'],failed_operation,'e'*64)
        class FailAfterDataAdapter(target.UmamiAdapter):
            fault=True
            def apply(self,payload,operation_id):
                value=super().apply(payload,operation_id)
                if self.fault:
                    self.fault=False
                    raise target.TargetError('controlled failure before terminal receipt and traffic resume')
                return value
        failed_adapter=FailAfterDataAdapter(tc)
        class FailedTargetTransport(restore.RemoteTransport):
            def _call(self,command,stream=None):
                return target.dispatch(tc,command,stream if stream is not None else io.BytesIO(),failed_adapter)
        failed_transport=FailedTargetTransport(cfg,failed_request)
        restore.preflight(cfg,failed_request,store,failed_transport)
        try:
            restore.apply(cfg,failed_request,store,failed_transport,safety)
            raise RuntimeError('controlled target failure was not observed')
        except target.TargetError:
            pass
        assert store.load(failed_operation)['state']=='failed'
        assert target.TargetJournalStore(tc.journal_root).load(failed_operation)['maintenance_active'] is True
        traffic(root,503)
        recovery_hash='f'*64
        recovered=restore.rollback(cfg,failed_request,recovery_hash,store,failed_transport,
                    lambda snapshot,purpose,descriptor: restore.stage_rollback(cfg,failed_request,recovery_hash,
                                                               failed_transport,snapshot,purpose,descriptor))
        assert recovered['state']=='rolled-back' and database(root,'SELECT proof FROM dev34_rehearsal_marker;')==b'D'
        traffic(root,200)
        report['scenarios'].append({'scenario':'controlled failure retains real maintenance and rolls back pinned safety data', 'status':'PASS'})
        report['status']='PASS'
    except Exception as exc:
        report.update(status='FAIL', error_class=type(exc).__name__)
        native.atomic_json(root/'report.json',report)
        print(json.dumps(report,sort_keys=True))
        raise
    finally:
        # Remove only this run's two explicitly named Compose projects. Bind data
        # and reports remain for inspection; prior fixtures/containers untouched.
        for edge in (True,False):
            subprocess.run(compose(root,'down','--volumes',edge=edge),stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
        if baseline - native.inventory(): raise RuntimeError('pre-existing container inventory changed')
    native.atomic_json(root/'report.json',report)
    print(json.dumps(report,sort_keys=True))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
