name: Example caller for reusable CI

on:
  workflow_dispatch:

jobs:
  ci:
    uses: marcel-tuinstra/devops/.github/workflows/reusable-ci.yml@c21f62bc7203d12474e46f1ff51b32a8cab4e116 # main
    with:
      node-version: "24"
      workdir: "."
      test-command: npm test
